//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoCSharp.Server {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LogFormats {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LogFormats() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoCSharp.Server.LogFormats", typeof(LogFormats).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&amp;(darkblue)Alliance&amp;(default)] Created -&gt; &amp;(darkcyan){0}&amp;(default) by account &amp;(darkcyan){1}&amp;(default)..
        /// </summary>
        internal static string Alliance_Created {
            get {
                return ResourceManager.GetString("Alliance_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&amp;(darkblue)Alliance&amp;(default)] Data -&gt; &amp;(darkcyan){0}&amp;(default) Requested by account &amp;(darkcyan){1}&amp;(default)..
        /// </summary>
        internal static string Alliance_Data_Requested {
            get {
                return ResourceManager.GetString("Alliance_Data_Requested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&amp;(darkmagenta)Attack&amp;(default)] Account &amp;(darkcyan){0}&amp;(default) attacked NPC &amp;(darkcyan){1}&amp;(default)..
        /// </summary>
        internal static string Attack_Npc {
            get {
                return ResourceManager.GetString("Attack_Npc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&amp;(darkmagenta)Attack&amp;(default)] Account &amp;(darkcyan){0}&amp;(default) attacked village &amp;(darkcyan){1}&amp;(default)..
        /// </summary>
        internal static string Attack_PvP {
            get {
                return ResourceManager.GetString("Attack_PvP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&amp;(darkmagenta)Attack&amp;(default)] Account &amp;(darkcyan){0}&amp;(default) returned home..
        /// </summary>
        internal static string Attack_ReturnHome {
            get {
                return ResourceManager.GetString("Attack_ReturnHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&amp;(darkmagenta)Avatar&amp;(default)] Profile &amp;(darkcyan){0}&amp;(default) was requested..
        /// </summary>
        internal static string Avatar_ProfileReq {
            get {
                return ResourceManager.GetString("Avatar_ProfileReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&amp;(darkyellow)Listener&amp;(default)] -&gt; New connection accepted &amp;(darkcyan){0}&amp;(default)..
        /// </summary>
        internal static string Listener_Connected {
            get {
                return ResourceManager.GetString("Listener_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&amp;(darkyellow)Listener&amp;(default)] -&gt; Avatar &amp;(darkcyan){0}&amp;(default) disconnected..
        /// </summary>
        internal static string Listener_Disconnected {
            get {
                return ResourceManager.GetString("Listener_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&amp;(darkgreen)Logic&amp;(default)] Clearing -&gt; &amp;(darkyellow)Cancelled&amp;(default) for account &amp;(darkcyan){0}&amp;(default) 
        ///at {1},{2}.
        /// </summary>
        internal static string Logic_Clearing_Cancelled {
            get {
                return ResourceManager.GetString("Logic_Clearing_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&amp;(darkgreen)Logic&amp;(default)] Clearing -&gt; &amp;(green)Finished&amp;(default) for account &amp;(darkcyan){0}&amp;(default) 
        ///at {1},{2}.
        /// </summary>
        internal static string Logic_Clearing_Finished {
            get {
                return ResourceManager.GetString("Logic_Clearing_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&amp;(darkgreen)Logic&amp;(default)] Clearing -&gt; Started for account &amp;(darkcyan){0}&amp;(default) 
        ///at {1},{2}.
        /// </summary>
        internal static string Logic_Clearing_Started {
            get {
                return ResourceManager.GetString("Logic_Clearing_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&amp;(darkgreen)Logic&amp;(default)] Construction -&gt; &amp;(red)Error:&amp;(default) for account &amp;(darkcyan){0}&amp;(default) 
        ///already in construction with ID {1}.
        /// </summary>
        internal static string Logic_Construction_AlreadyConstructing {
            get {
                return ResourceManager.GetString("Logic_Construction_AlreadyConstructing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&amp;(darkgreen)Logic&amp;(default)] Construction -&gt; &amp;(darkyellow)Cancelled&amp;(default) for account &amp;(darkcyan){0}&amp;(default) 
        ///at {1},{2} with lvl {3}.
        /// </summary>
        internal static string Logic_Construction_Cancelled {
            get {
                return ResourceManager.GetString("Logic_Construction_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&amp;(darkgreen)Logic&amp;(default)] Construction -&gt; &amp;(green)Finished&amp;(default) for account &amp;(darkcyan){0}&amp;(default) 
        ///at {1},{2} with lvl {3}.
        /// </summary>
        internal static string Logic_Construction_Finished {
            get {
                return ResourceManager.GetString("Logic_Construction_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&amp;(darkgreen)Logic&amp;(default)] Construction -&gt; &amp;(red)Error:&amp;(default) for account &amp;(darkcyan){0}&amp;(default) 
        ///not in construction with ID {1}.
        /// </summary>
        internal static string Logic_Construction_NotConstructing {
            get {
                return ResourceManager.GetString("Logic_Construction_NotConstructing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&amp;(darkgreen)Logic&amp;(default)] Construction -&gt; Started for account &amp;(darkcyan){0}&amp;(default)
        ///at {1},{2} with lvl {3}.
        /// </summary>
        internal static string Logic_Construction_Started {
            get {
                return ResourceManager.GetString("Logic_Construction_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&amp;(darkgreen)Logic&amp;(default)] Decoration -&gt; Bought &amp;(darkcyan){0}&amp;(default) for account &amp;(darkcyan){1}&amp;(default) 
        ///at {2},{3}.
        /// </summary>
        internal static string Logic_Deco_Bought {
            get {
                return ResourceManager.GetString("Logic_Deco_Bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&amp;(darkgreen)Logic&amp;(default)] Decoration -&gt; Sold &amp;(darkcyan){0}&amp;(default) for account &amp;(darkcyan){1}&amp;(default) 
        ///at {2},{3}.
        /// </summary>
        internal static string Logic_Deco_Sold {
            get {
                return ResourceManager.GetString("Logic_Deco_Sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&amp;(darkgreen)Logic&amp;(default)] Placement -&gt; Moved &amp;(darkcyan){0}&amp;(default) for account &amp;(darkcyan){1}&amp;(default)
        ///at {2},{3}.
        /// </summary>
        internal static string Logic_Placement_VillageObjectMoved {
            get {
                return ResourceManager.GetString("Logic_Placement_VillageObjectMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&amp;(darkgreen)Logic&amp;(default)] Rearmed -&gt; &amp;(darkcyan){0}&amp;(default) for account &amp;(darkcyan){1}&amp;(default) 
        ///at {2},{3}.
        /// </summary>
        internal static string Logic_Rearmed_Trap {
            get {
                return ResourceManager.GetString("Logic_Rearmed_Trap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&amp;(darkgreen)Logic&amp;(default)] Bought resource -&gt; {1} for account &amp;(darkcyan){0}&amp;(default)
        ///Amount: {2}.
        /// </summary>
        internal static string Logic_Resources_Bought {
            get {
                return ResourceManager.GetString("Logic_Resources_Bought", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&amp;(darkgreen)Logic&amp;(default)] Unlocked -&gt; &amp;(darkcyan){0}&amp;(default) for account &amp;(darkcyan){1}&amp;(default) 
        ///at {2},{3}.
        /// </summary>
        internal static string Logic_Unlocked_Building {
            get {
                return ResourceManager.GetString("Logic_Unlocked_Building", resourceCulture);
            }
        }
    }
}
